USE hike;

# What are the top 10 shortest duration easy trails?
DROP PROCEDURE IF EXISTS getDurationTrails_ShortE; 
DELIMITER $$ 
CREATE PROCEDURE getDurationTrails_ShortE() BEGIN SELECT td.trailDurationMin AS Top10ShortestDurationEasyTrails, t.trailName, t.trailState, t.trailRegion FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Easy' ORDER BY Top10ShortestDurationEasyTrails ASC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getDurationTrails_ShortE();

# What are the top 10 longest duration easy trails?
DROP PROCEDURE IF EXISTS getDurationTrails_LongE; 
DELIMITER $$ 
CREATE PROCEDURE getDurationTrails_LongE() BEGIN SELECT td.trailDurationMin AS Top10LongestDurationEasyTrails, t.trailName, t.trailState, t.trailRegion FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Easy' ORDER BY Top10LongestDurationEasyTrails DESC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getDurationTrails_LongE();

# What are the top 10 shortest duration intermediate trails?
DROP PROCEDURE IF EXISTS getDurationTrails_ShortI; 
DELIMITER $$ 
CREATE PROCEDURE getDurationTrails_ShortI() BEGIN SELECT td.trailDurationMin AS Top10ShortestDurationIntermediateTrails, t.trailName, t.trailState, t.trailRegion, ti.trailDifficulty FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Intermediate' ORDER BY Top10ShortestDurationIntermediateTrails ASC LIMIT 10; 
END$$
DELIMITER ;
CALL getDurationTrails_ShortI();

# What are the top 10 longest duration intermediate trails?
DROP PROCEDURE IF EXISTS getDurationTrails_LongI; 
DELIMITER $$ 
CREATE PROCEDURE getDurationTrails_LongI() BEGIN SELECT td.trailDurationMin AS Top10LongestDurationIntermediateTrails, t.trailName, t.trailState, t.trailRegion, ti.trailDifficulty FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Intermediate' ORDER BY Top10LongestDurationIntermediateTrails DESC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getDurationTrails_LongI();

# What are the top 10 shortest duration advanced trails?
DROP PROCEDURE IF EXISTS getDurationTrails_ShortA; 
DELIMITER $$ 
CREATE PROCEDURE getDurationTrails_ShortA() BEGIN SELECT td.trailDurationMin AS Top10ShortestDurationAdvancedTrails, t.trailName, t.trailState, t.trailRegion, ti.trailDifficulty FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Advanced' ORDER BY Top10ShortestDurationAdvancedTrails ASC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getDurationTrails_ShortA();

# What are the top 10 longest duration advanced trails?
DROP PROCEDURE IF EXISTS getDurationTrails_LongA; 
DELIMITER $$ 
CREATE PROCEDURE getDurationTrails_LongA() BEGIN SELECT td.trailDurationMin AS Top10LongestDurationAdvancedTrails, t.trailName, t.trailState, t.trailRegion, ti.trailDifficulty FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Advanced' ORDER BY Top10LongestDurationAdvancedTrails DESC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getDurationTrails_LongA();

# What is the average DURATION of easy, intermediate, and advanced trails?
SELECT AVG(td.trailDurationMin) AS AverageDurationMin, ti.trailDifficulty FROM trailDetails td, trailInfo ti WHERE td.trailID = ti.trailID AND ti.trailDifficulty = 'Easy' UNION ALL
SELECT AVG(td.trailDurationMin) AS AverageDurationMin, ti.trailDifficulty FROM trailDetails td, trailInfo ti WHERE td.trailID = ti.trailID AND ti.trailDifficulty = 'Intermediate' UNION ALL
SELECT AVG(td.trailDurationMin) AS AverageDurationMin, ti.trailDifficulty FROM trailDetails td, trailInfo ti WHERE td.trailID = ti.trailID AND ti.trailDifficulty = 'Advanced';

# What is the average duration of easy trails in every state?
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alabama' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alaska' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arizona' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arkansas' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'California' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Colorado' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Connecticut' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Delaware' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Florida' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Georgia' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Hawaii' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Idaho' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Illinois' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Indiana' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Iowa' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kansas' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kentucky' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Louisiana' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maine' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maryland' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Massachusetts' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Michigan' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Minnesota' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Mississippi' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Missouri' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Montana' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nebraska' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nevada' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Hampshire' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Jersey' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Mexico' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New York' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Carolina' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Dakota' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Ohio' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oklahoma' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oregon' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Pennsylvania' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Rhode Island' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Carolina' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Dakota' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Tennessee' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Texas' AND ti.trailDifficulty = 'Easy' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Utah' AND ti.trailDifficulty = 'Easy' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Vermont' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Virginia' AND ti.trailDifficulty = 'Easy' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Washington' AND ti.trailDifficulty = 'Easy' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'West Virginia' AND ti.trailDifficulty = 'Easy' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wisconsin' AND ti.trailDifficulty = 'Easy' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wyoming' AND ti.trailDifficulty = 'Easy'
ORDER BY AverageTrailDurationInMinEasy DESC;

# What is the average duration of intermediate trails in every state?
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alabama' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alaska' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arizona' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arkansas' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'California' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Colorado' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Connecticut' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Delaware' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Florida' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Georgia' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Hawaii' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Idaho' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Illinois' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Indiana' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Iowa' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kansas' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kentucky' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Louisiana' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maine' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maryland' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Massachusetts' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Michigan' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Minnesota' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Mississippi' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Missouri' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Montana' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nebraska' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nevada' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Hampshire' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Jersey' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Mexico' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New York' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Carolina' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Dakota' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Ohio' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oklahoma' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oregon' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Pennsylvania' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Rhode Island' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Carolina' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Dakota' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Tennessee' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Texas' AND ti.trailDifficulty = 'Intermediate' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Utah' AND ti.trailDifficulty = 'Intermediate' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Vermont' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Virginia' AND ti.trailDifficulty = 'Intermediate' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Washington' AND ti.trailDifficulty = 'Intermediate' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'West Virginia' AND ti.trailDifficulty = 'Intermediate' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wisconsin' AND ti.trailDifficulty = 'Intermediate' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wyoming' AND ti.trailDifficulty = 'Intermediate'
ORDER BY AverageTrailDurationInMinIntermediate DESC;

# What is the average duration of advanced trails in every state?
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alabama' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alaska' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arizona' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arkansas' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'California' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Colorado' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Connecticut' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Delaware' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Florida' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Georgia' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Hawaii' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Idaho' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Illinois' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Indiana' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Iowa' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kansas' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kentucky' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Louisiana' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maine' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maryland' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Massachusetts' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Michigan' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Minnesota' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Mississippi' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Missouri' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Montana' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nebraska' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nevada' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Hampshire' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Jersey' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Mexico' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New York' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Carolina' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Dakota' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Ohio' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oklahoma' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oregon' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Pennsylvania' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Rhode Island' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Carolina' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Dakota' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Tennessee' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Texas' AND ti.trailDifficulty = 'Advanced' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Utah' AND ti.trailDifficulty = 'Advanced' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Vermont' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Virginia' AND ti.trailDifficulty = 'Advanced' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Washington' AND ti.trailDifficulty = 'Advanced' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'West Virginia' AND ti.trailDifficulty = 'Advanced' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wisconsin' AND ti.trailDifficulty = 'Advanced' UNION ALL
SELECT ROUND(AVG(td.trailDurationMin), 1) AS AverageTrailDurationInMinAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wyoming' AND ti.trailDifficulty = 'Advanced'
ORDER BY AverageTrailDurationInMinAdvanced DESC;