USE hike; 

# What are the top 10 shortest length easy trails?
DROP PROCEDURE IF EXISTS getLengthTrails_ShortE; 
DELIMITER $$ 
CREATE PROCEDURE getLengthTrails_ShortE() BEGIN SELECT td.trailLengthMi AS Top10ShortestEasy, t.trailName, t.trailState, t.trailRegion, ti.trailRating FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Easy' ORDER BY Top10ShortestEasy ASC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getLengthTrails_ShortE();

# What are the top 10 longest length easy trails?
DROP PROCEDURE IF EXISTS getLengthTrails_LongE; 
DELIMITER $$ 
CREATE PROCEDURE getLengthTrails_LongE() BEGIN SELECT td.trailLengthMi AS Top10LongestEasy, t.trailName, t.trailState, t.trailRegion, ti.trailRating FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Easy' ORDER BY Top10LongestEasy DESC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getLengthTrails_LongE();

# What are the top 10 shortest length intermediate trails?
DROP PROCEDURE IF EXISTS getLengthTrails_ShortI; 
DELIMITER $$ 
CREATE PROCEDURE getLengthTrails_ShortI() BEGIN SELECT td.trailLengthMi AS Top10ShortestIntermediate, t.trailName, t.trailState, t.trailRegion, ti.trailRating FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Intermediate' ORDER BY Top10ShortestIntermediate ASC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getLengthTrails_ShortI();

# What are the top 10 longest length intermediate trails?
DROP PROCEDURE IF EXISTS getLengthTrails_LongI; 
DELIMITER $$ 
CREATE PROCEDURE getLengthTrails_LongI() BEGIN SELECT td.trailLengthMi AS Top10LongestIntermediate, t.trailName, t.trailState, t.trailRegion, ti.trailRating FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Intermediate' ORDER BY Top10LongestIntermediate DESC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getLengthTrails_LongI();

# What are the top 10 shortest length advanced trails?
DROP PROCEDURE IF EXISTS getLengthTrails_ShortA; 
DELIMITER $$ 
CREATE PROCEDURE getLengthTrails_ShortA() BEGIN SELECT td.trailLengthMi AS Top10ShortestAdvanced, t.trailName, t.trailState, t.trailRegion, ti.trailRating FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Advanced' ORDER BY Top10ShortestAdvanced ASC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getLengthTrails_ShortA();

# What are the top 10 longest length advanced trails?
DROP PROCEDURE IF EXISTS getLengthTrails_LongA; 
DELIMITER $$ 
CREATE PROCEDURE getLengthTrails_LongA() BEGIN SELECT td.trailLengthMi AS Top10LongestAdvancedTrails, t.trailName, t.trailState, t.trailRegion FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Advanced' ORDER BY Top10LongestAdvancedTrails DESC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getLengthTrails_LongA();

# What is the average length of easy, intermediate, and advanced trails?
SELECT AVG(td.trailLengthMi) AS AverageLengthInMiles, ti.trailDifficulty FROM trailDetails td, trailInfo ti WHERE td.trailID = ti.trailID AND ti.trailDifficulty = 'Easy' UNION ALL
SELECT AVG(td.trailLengthMi) AS AverageLengthInMiles, ti.trailDifficulty FROM trailDetails td, trailInfo ti WHERE td.trailID = ti.trailID AND ti.trailDifficulty = 'Intermediate'UNION ALL 
SELECT AVG(td.trailLengthMi) AS AverageLengthInMiles, ti.trailDifficulty FROM trailDetails td, trailInfo ti WHERE td.trailID = ti.trailID AND ti.trailDifficulty = 'Advanced';

# What is the average length of easy trails in every state?
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alabama' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alaska' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arizona' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arkansas' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'California' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Colorado' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Connecticut' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Delaware' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Florida' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Georgia' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Hawaii' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Idaho' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Illinois' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Indiana' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Iowa' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kansas' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kentucky' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Louisiana' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maine' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maryland' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Massachusetts' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Michigan' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Minnesota' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Mississippi' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Missouri' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Montana' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nebraska' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nevada' AND ti.trailDifficulty = 'Easy'  UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Hampshire' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Jersey' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Mexico' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New York' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Carolina' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Dakota' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Ohio' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oklahoma' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oregon' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Pennsylvania' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Rhode Island' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Carolina' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Dakota' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Tennessee' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Texas' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Utah' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Vermont' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Virginia' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Washington' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'West Virginia' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wisconsin' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wyoming' AND ti.trailDifficulty = 'Easy' 
ORDER BY AverageTrailLengthInMiEasy DESC;

# What is the average length of intermediate trails in every state?
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alabama' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alaska' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arizona' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arkansas' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'California' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Colorado' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Connecticut' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Delaware' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Florida' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Georgia' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Hawaii' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Idaho' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Illinois' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Indiana' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Iowa' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kansas' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kentucky' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Louisiana' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maine' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maryland' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Massachusetts' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Michigan' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Minnesota' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Mississippi' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Missouri' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Montana' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nebraska' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nevada' AND ti.trailDifficulty = 'Intermediate'  UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Hampshire' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Jersey' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Mexico' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New York' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Carolina' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Dakota' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Ohio' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oklahoma' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oregon' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Pennsylvania' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Rhode Island' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Carolina' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Dakota' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Tennessee' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Texas' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Utah' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Vermont' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Virginia' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Washington' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'West Virginia' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wisconsin' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wyoming' AND ti.trailDifficulty = 'Intermediate' 
ORDER BY AverageTrailLengthInMiIntermediate DESC;

# What is the average length of advanced trails in every state?
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alabama' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alaska' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arizona' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arkansas' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'California' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Colorado' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Connecticut' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Delaware' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Florida' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Georgia' AND ti.trailDifficulty = 'Advanced'  UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Hawaii' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Idaho' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Illinois' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Indiana' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Iowa' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kansas' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kentucky' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Louisiana' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maine' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maryland' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Massachusetts' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Michigan' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Minnesota' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Mississippi' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Missouri' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Montana' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nebraska' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nevada' AND ti.trailDifficulty = 'Advanced'  UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Hampshire' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Jersey' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Mexico' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New York' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Carolina' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Dakota' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Ohio' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oklahoma' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oregon' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Pennsylvania' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Rhode Island' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Carolina' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Dakota' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Tennessee' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Texas' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Utah' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Vermont' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Virginia' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Washington' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'West Virginia' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wisconsin' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailLengthMi), 1) AS AverageTrailLengthInMiAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wyoming' AND ti.trailDifficulty = 'Advanced' 
ORDER BY AverageTrailLengthInMiAdvanced DESC;