USE hike;

# What are the top 10 lowest elevation easy trails?
DROP PROCEDURE IF EXISTS getElevationTrails_LowE; 
DELIMITER $$ 
CREATE PROCEDURE getElevationTrails_LowE() BEGIN SELECT td.trailElevationFt AS Top10LowestElevationEasyTrails, t.trailName, t.trailState, t.trailRegion, ti.trailRating FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Easy' ORDER BY Top10LowestElevationEasyTrails ASC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getElevationTrails_LowE();

# What are the top 10 highest elevation easy trails?
DROP PROCEDURE IF EXISTS getElevationTrails_HighE; 
DELIMITER $$ 
CREATE PROCEDURE getElevationTrails_HighE() BEGIN SELECT td.trailElevationFt AS Top10HighestElevationEasyTrails, t.trailName, t.trailState, t.trailRegion, ti.trailRating FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Easy' ORDER BY Top10HighestElevationEasyTrails DESC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getElevationTrails_HighE();

# What are the top 10 lowest elevation intermediate trails?
DROP PROCEDURE IF EXISTS getElevationTrails_LowI; 
DELIMITER $$ 
CREATE PROCEDURE getElevationTrails_LowI() BEGIN SELECT td.trailElevationFt AS Top10LowestElevationIntermediateTrails, t.trailName, t.trailState, t.trailRegion, ti.trailRating FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Intermediate' ORDER BY Top10LowestElevationIntermediateTrails ASC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getElevationTrails_LowI();

# What are the top 10 highest elevation intermediate trails?
DROP PROCEDURE IF EXISTS getElevationTrails_HighI; 
DELIMITER $$ 
CREATE PROCEDURE getElevationTrails_HighI() BEGIN SELECT td.trailElevationFt AS Top10HighestElevationIntermediateTrails, t.trailName, t.trailState, t.trailRegion, ti.trailRating FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Intermediate' ORDER BY Top10HighestElevationIntermediateTrails DESC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getElevationTrails_HighI();

# What are the top 10 lowest elevation advanced trails?
DROP PROCEDURE IF EXISTS getElevationTrails_LowA; 
DELIMITER $$ 
CREATE PROCEDURE getElevationTrails_LowA() BEGIN SELECT td.trailElevationFt AS Top10LowestElevationAdvancedTrails, t.trailName, t.trailState, t.trailRegion, ti.trailRating FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Advanced' ORDER BY Top10LowestElevationAdvancedTrails ASC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getElevationTrails_LowA();

# What are the top 10 highest elevation advanced trails?
DROP PROCEDURE IF EXISTS getElevationTrails_HighA; 
DELIMITER $$ 
CREATE PROCEDURE getElevationTrails_HighA() BEGIN SELECT td.trailElevationFt AS Top10HighestElevationAdvancedTrails, t.trailName, t.trailState, t.trailRegion, ti.trailRating FROM trails t, trailDetails td, trailInfo ti WHERE t.trailID = td.trailID AND t.trailID = ti.trailID AND ti.trailDifficulty = 'Advanced' ORDER BY Top10HighestElevationAdvancedTrails DESC LIMIT 10; 
END$$ 
DELIMITER ;
CALL getElevationTrails_HighA();

# What is the average elevation of easy, intermediate, and advanced trails?
SELECT AVG(td.trailElevationFt) AS AverageElevation, ti.trailDifficulty FROM trailDetails td, trailInfo ti WHERE td.trailID = ti.trailID AND ti.trailDifficulty = 'Easy' UNION ALL
SELECT AVG(td.trailElevationFt) AS AverageElevation, ti.trailDifficulty FROM trailDetails td, trailInfo ti WHERE td.trailID = ti.trailID AND ti.trailDifficulty = 'Intermediate' UNION ALL
SELECT AVG(td.trailElevationFt) AS AverageElevation, ti.trailDifficulty FROM trailDetails td, trailInfo ti WHERE td.trailID = ti.trailID AND ti.trailDifficulty = 'Advanced';

# What is the average elevation of easy trails in every state? 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alabama' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alaska' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arizona' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arkansas' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'California' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Colorado' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Connecticut' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Delaware' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID  AND td.trailID = t.trailID AND t.trailState = 'Florida' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Georgia' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Hawaii' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Idaho' AND ti.trailDifficulty = 'Easy' UNION ALL
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Illinois' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Indiana' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Iowa' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kansas' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kentucky' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Louisiana' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maine' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maryland' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Massachusetts' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Michigan' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Minnesota' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Mississippi' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Missouri' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Montana' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nebraska' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nevada' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Hampshire' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Jersey' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Mexico' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New York' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Carolina' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Dakota' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Ohio' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oklahoma' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oregon' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Pennsylvania' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Rhode Island' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Carolina' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Dakota' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Tennessee' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Texas' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Utah' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Vermont' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Virginia' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Washington' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'West Virginia' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wisconsin' AND ti.trailDifficulty = 'Easy' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtEasy, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wyoming' AND ti.trailDifficulty = 'Easy'
ORDER BY AverageTrailElevationInFtEasy DESC;

# What is the average elevation of intermediate trails in every state? 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alabama' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alaska' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arizona' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arkansas' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'California' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Colorado' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Connecticut' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Delaware' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID  AND td.trailID = t.trailID AND t.trailState = 'Florida' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Georgia' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Hawaii' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Idaho' AND ti.trailDifficulty = 'Intermediate' UNION ALL
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Illinois' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Indiana' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Iowa' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kansas' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kentucky' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Louisiana' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maine' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maryland' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Massachusetts' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Michigan' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Minnesota' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Mississippi' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Missouri' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Montana' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nebraska' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nevada' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Hampshire' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Jersey' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Mexico' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New York' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Carolina' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Dakota' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Ohio' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oklahoma' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oregon' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Pennsylvania' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Rhode Island' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Carolina' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Dakota' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Tennessee' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Texas' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Utah' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Vermont' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Virginia' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Washington' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'West Virginia' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wisconsin' AND ti.trailDifficulty = 'Intermediate' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtIntermediate, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wyoming' AND ti.trailDifficulty = 'Intermediate'
ORDER BY AverageTrailElevationInFtIntermediate DESC;

# What is the average elevation of advanced trails in every state?
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alabama' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Alaska' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arizona' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Arkansas' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'California' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Colorado' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Connecticut' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Delaware' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Florida' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Georgia' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Hawaii' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Idaho' AND ti.trailDifficulty = 'Advanced' UNION ALL
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Illinois' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Indiana' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Iowa' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kansas' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Kentucky' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Louisiana' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maine' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Maryland' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Massachusetts' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Michigan' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Minnesota' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Mississippi' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Missouri' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Montana' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nebraska' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Nevada' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Hampshire' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Jersey' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New Mexico' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'New York' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Carolina' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'North Dakota' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Ohio' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oklahoma' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Oregon' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Pennsylvania' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Rhode Island' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Carolina' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'South Dakota' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Tennessee' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Texas' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Utah' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Vermont' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Virginia' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Washington' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'West Virginia' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wisconsin' AND ti.trailDifficulty = 'Advanced' UNION ALL 
SELECT ROUND(AVG(td.trailElevationFt), 1) AS AverageTrailElevationInFtAdvanced, t.trailState FROM trails t, trailInfo ti, trailDetails td WHERE t.trailID = ti.trailID AND td.trailID = t.trailID AND t.trailState = 'Wyoming' AND ti.trailDifficulty = 'Advanced'
ORDER BY AverageTrailElevationInFtAdvanced DESC;